# Generated by Django 2.2.19 on 2023-05-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='RecipeIngredient',
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table='recipes_recipe_ingredient',
        ),
    ]
