# Generated by Django 2.2.19 on 2023-05-22 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230519_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipeRelation',
            new_name='IngredientRecipe',
        ),
    ]
