# Generated by Django 3.2.19 on 2023-06-17 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
