# Generated by Django 3.2.19 on 2023-06-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230619_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipes.ingredient', verbose_name='Ингредиенты'),
            preserve_default=False,
        ),
    ]
